# Generated by Django 3.0.8 on 2020-07-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Streamers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=30)),
                ('channel_id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('bio', models.CharField(max_length=30)),
                ('logo', models.CharField(max_length=30)),
                ('banner', models.CharField(max_length=30)),
            ],
        ),
    ]
